--inserting data into KEYWORDS table
INSERT INTO KEYWORDS VALUES ('BEACH');
INSERT INTO KEYWORDS VALUES ('SUNNY');
INSERT INTO KEYWORDS VALUES ('MUSEUM');
INSERT INTO KEYWORDS VALUES ('VOLLEY BALL');
INSERT INTO KEYWORDS VALUES ('WATER');
INSERT INTO KEYWORDS VALUES ('SUN');